# Generated by Django 2.2.10 on 2021-09-15 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(auto_created=True, default=datetime.date.today, verbose_name='Начало опроса'),
        ),
    ]
